config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "rec_entries#home"
  get 'rec_entries/:name/(:cursor)', to: 'rec_entries#show_rec_file', as: :rec_file
  match 'rec_entries/update', to: 'rec_entries#update', as: :update_rec_entry, via: [:put, :patch]
  get 'benchmark/:name', to: 'rec_entries#benchmark'
  get 'find_entries', to: "rec_entries#find_entries"
  resources :variations, only: [:new, :create] do
    post :build_variation_modal, on: :collection, as: :build_variation_modal
    get "cancel_job/:id", to: "variations#destroy", on: :collection, as: :cancel_job
  end
end

app/views/shared/_entry.slim
tr class=cycle('bg-blue-100', 'bg-blue-200') class="h-14" id=entry.oid.gsub(".", "")
  td
    span.pl-2 = entry.id
  td.overflow-scroll
    p.oid = entry.oid
    p = entry.translation if entry.translation
  td.p-2
    span = sanitize(get_type(entry.tag))
  td class="m-auto mx-4 overflow-x-scroll flex justify-end mr-2"
    = render(partial: "shared/entry_form", locals:{entry: entry, name: @name})
    = render(partial: "shared/variate_button", locals:{entry: entry, name: @name}) if is_numeric?(entry.tag)

app/views/shared/_entry_form.slim
= form_with(url: "#{update_rec_entry_path}##{entry.oid.gsub(".", "")}", id: "update-#{entry.oid.gsub(".","")}",  method: "put", class: "flex w-full items-center my-1") do |f|
  = f.hidden_field :name, value: name
  = f.hidden_field :oid, value: entry.oid
  - f.hidden_field :from_entry_form, value: true
  - if is_numeric?(entry.tag)
    = f.number_field :value, id: "value-#{entry.oid}", value: entry.value.to_i, class: "w-4/5 p-2 rounded"
  - else
    /! Line underneath creates issues with dahua.snmprec
    = f.text_area :value, class: "p-2 rounded w-4/5", value: is_hex_or_ascii_string?(entry.tag) ? decode_value(entry).html_safe : entry.value.strip
  = f.submit "change", class: "button rounded ml-2 px-2 update-entry"

app/views/shared/_error.slim
#flash-error.fixed.top-0.inset-x-0.pb-2.sm:pb-5
  .max-w-7xl.mx-auto.px-2.sm:px-6.lg:px-8
    .p-2.rounded-lg.bg-red-600.shadow-lg.sm:p-3
      .flex.items-center.justify-between.flex-wrap
        .w-0.flex-1.flex.items-center
          span.flex.p-2.rounded-lg.bg-indigo-800
            /! Heroicon name: outline/speakerphone
            svg.h-6.w-6.text-white aria-hidden="true" fill="none" stroke="currentColor" viewbox=("0 0 24 24") xmlns="http://www.w3.org/2000/svg"
              path d=("M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z") stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          p.ml-3.font-medium.text-black.truncate
            span.hidden.md:inline
              = local_assigns[:message]
        .order-2.flex-shrink-0.sm:order-3.sm:ml-2
          button#dismiss.-mr-1.flex.p-2.rounded-md.hover:bg-black-500.focus:outline-none.focus:ring-2.focus:ring-white type="button"
            span.sr-only Dismiss
            /! Heroicon name: outline/x
            svg.h-6.w-6.text-white aria-hidden="true" fill="none" stroke="currentColor" viewbox=("0 0 24 24") xmlns="http://www.w3.org/2000/svg"
              path d=("M6 18L18 6M6 6l12 12") stroke-linecap="round" stroke-linejoin="round" stroke-width="2"

app/views/shared/_load_all.slim
- cursor = local_assigns[:cursor]
= link_to "LOAD ALL", rec_file_path(params: {cursor: @cursor, request_type: "show_all"}), remote: true, class: "mt-2 m-auto inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/shared/_load_more.slim
- cursor = local_assigns[:cursor]
= link_to "LOAD 100 MORE", rec_file_path(params: {cursor: @cursor, request_type: "show_100"}), remote: true, class: "mt-2 m-auto inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/shared/_results.slim
#results-modal.fixed.z-10.inset-0.overflow-y-auto x-data="{open: true}" x-show="open" @click.away="open = false"
  .flex.items-end.justify-center.min-h-screen.pt-4.px-4.pb-20.text-center.sm:block.sm:p-0
    #background.origin-top-right.absolute.right-0.mt-2.w-full.rounded-md.shadow-lg aria-hidden="true" class=("fixed inset-0 transition-opacity") x-show="open" x-transition:enter=("transition ease-out duration-100 transform") x-transition:enter-end=("opacity-100 scale-100") x-transition:enter-start=("opacity-0 scale-95") x-transition:leave=("transition ease-in duration-75 transform") x-transition:leave-end=("opacity-0 scale-95") x-transition:leave-start=("opacity-100 scale-100")
      .absolute.inset-0.bg-gray-500.opacity-75
    /! This element is to trick the browser into centering the modal contents.
    span.hidden.sm:inline-block.sm:align-middle.sm:h-screen aria-hidden="true"
    #panel.inline-block.align-bottom.bg-white.rounded-lg.px-4.pt-5.pb-4.text-left.overflow-hidden.shadow-xl.transform.transition-all.sm:my-8.sm:align-middle.sm:p-6 aria-labelledby="modal-headline" @click.away="open = false" aria-modal="true" class="lg:w-3/5 md:w-3/5" role="dialog"
      .mx-auto.flex.flex-row.items-center.justify-center.h-12.w-12.rounded-full class="w-1/2 #{@warning || (@count.zero?) ? 'bg-red-100' : 'bg-green-100'}"
        .text-lg
          -if @count > 0
            = pluralize(@count, 'OID')
            | &nbsp found
          - else
            = "No OID found"
      .mt-3.text-center.sm:mt-5
        - if @warning
          = @warning
        .flex.w-full.flex-row.flex-wrap.place-content-center
          input.rounded.border-2.p-3 class="bg-purple-white.shadow w-10/12" data-filename="#{@name}" type="search" value="#{@oid}" class="w-full" id="modal-js-search"
          - if @entries.size >= 1
            table.border.border-2.mt-2 class="w-10/12"
              thead
                tr
                  th.border class="w-1/2"  OID
                  th.border class="w-1/5"  TYPE
                  th.border class="w-1/2"  VALUE
                thead
                  tbody
                    - @entries.each do |entry|
                      tr class="#{cycle('bg-blue-100', 'bg-blue-200')} h-14"
                        td
                          span= entry.oid
                          br/
                          span= entry.translation
                        td
                          span= get_type(entry.tag)
                        td.m-auto.overflow-x-scroll
                          = render(partial: "shared/entry_form", locals:{entry: entry, name: @name})
                          = render(partial: "shared/variate_button", locals: {entry: entry}) if is_numeric?(entry.tag)

app/views/shared/_success.slim
#flash-success.fixed.top-0.inset-x-0.pb-2.sm:pb-5
  .max-w-7xl.mx-auto.px-2.sm:px-6.lg:px-8
    .p-2.rounded-lg.bg-indigo-600.shadow-lg.sm:p-3
      .flex.items-center.justify-between.flex-wrap
        .w-0.flex-1.flex.items-center
          span.flex.p-2.rounded-lg.bg-indigo-800
            /! Heroicon name: outline/speakerphone
            svg.h-6.w-6.text-white aria-hidden="true" fill="none" stroke="currentColor" viewbox=("0 0 24 24") xmlns="http://www.w3.org/2000/svg" 
              path d=("M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z") stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
          p.ml-3.font-medium.text-white.truncate
            span.hidden.md:inline
              = local_assigns[:message]
        .order-2.flex-shrink-0.sm:order-3.sm:ml-2
          button#dismiss.-mr-1.flex.p-2.rounded-md.hover:bg-indigo-500.focus:outline-none.focus:ring-2.focus:ring-white type="button" 
            span.sr-only Dismiss
            /! Heroicon name: outline/x
            svg.h-6.w-6.text-white aria-hidden="true" fill="none" stroke="currentColor" viewbox=("0 0 24 24") xmlns="http://www.w3.org/2000/svg" 
              path d=("M6 18L18 6M6 6l12 12") stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 

app/views/shared/_variate.slim
#variate-modal.fixed.z-10.inset-0.overflow-y-auto x-data="{open: #{@is_open}}" x-show="open" @click.away="open = false"
  .flex.items-end.justify-center.min-h-screen.pt-4.px-4.pb-20.text-center.sm:block.sm:p-0
    #background.origin-top-right.absolute.right-0.mt-2.w-full.shadow-lg aria-hidden="true" class=("fixed inset-0 transition-opacity") x-show="open" x-transition:enter=("transition ease-out duration-100 transform") x-transition:enter-end=("opacity-100 scale-100") x-transition:enter-start=("opacity-0 scale-95") x-transition:leave=("transition ease-in duration-75 transform") x-transition:leave-end=("opacity-0 scale-95") x-transition:leave-start=("opacity-100 scale-100")
      .absolute.inset-0.bg-gray-500.opacity-75
    /! This element is to trick the browser into centering the modal contents.
    span.hidden.sm:inline-block.sm:align-middle.sm:h-screen aria-hidden="true"
    #panel.inline-block.align-bottom.bg-white.rounded-lg.px-4.pt-5.pb-4.text-left.overflow-hidden.shadow-xl.transform.transition-all.sm:my-8.sm:align-middle.sm:p-6 aria-labelledby="modal-headline" @click.away="open = false" aria-modal="true" class="lg:w-3/5 md:w-3/5" role="dialog"
        h1 id="variation-title"
         = "Variation for #{@variation.oid}, current value: #{@variation.from}"
        .flex.w-full.flex-row.flex-wrap.place-content-center
          = form_for(Snmp::Variation.new, url: variations_path, method: :post, html: {class: "flex flex-col"}) do |f|
            = f.hidden_field :oid, value: @variation.oid, id: "variate-oid"
            = f.hidden_field :from, value: @variation.from, id: "variate-from"
            = f.hidden_field :filename, value: @variation.filename
            = f.label :to, class: "mr-2"
            = f.number_field :to, value: @variation.from, class: "border rounded-md", id:"variate-to"
            = f.label :duration, class: "mr-2"
            = f.number_field :duration, value: 20, min: 0, class: "border rounded-md"
            = f.label :interval, class: "mr-2"
            = f.number_field :interval, value: 5, min: 0, class: "border rounded-md"
            div.flex
              = check_box_tag(:linear)
              = label_tag(:linear, "Linear")
              = check_box_tag(:random)
              = label_tag(:random, "Random")
            = f.submit "start!", class: "button bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full update-entry"

app/views/shared/_variate_button.slim
= form_for entry.variation, url: {action: :build_variation_modal, controller: :variations}, remote: true do |f|
  = f.hidden_field :from, value: entry.variation.instance_variable_get(:@from)
  = f.hidden_field :oid, value: entry.variation.instance_variable_get(:@oid)
  = f.hidden_field :filename, value: @name
  = f.submit "Variate", id: "variate-#{entry.variation.instance_variable_get(:@oid)}", class: "button rounded ml-2 px-2 variate bg-blue-500 hover:bg-blue-700 text-white font-bold"